---
- name: Install Dependencies 
  apt:
    name={{item}}
    state=present 
    update_cache=yes
  with_items: dependencies
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: Install Dependencies 
  homebrew:
    name={{item}}
    state=present 
    update_homebrew=yes
  with_items: dependencies
  when: ansible_os_family == 'Darwin'

- name: Copy my .vimrc
  command: curl -LSso ~/.vimrc https://raw.github.com/ChengLong/configs/master/.vimrc
  sudo: no

- name: Make directory for Pathogen
  command: mkdir -p ~/.vim/autoload ~/.vim/bundle
  sudo: no

- name: Install Pathogen
  command: curl -LSso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
  sudo: no

- name: Install Solarized
  git: 
    repo=git://github.com/altercation/vim-colors-solarized.git 
    dest=~/.vim/bundle/vim-colors-solarized
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install Nerdtree 
  git: 
    repo=https://github.com/scrooloose/nerdtree.git
    dest=~/.vim/bundle/nerdtree
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install AutoComplPop 
  git: 
    repo=https://github.com/vim-scripts/AutoComplPop.git
    dest=~/.vim/bundle/AutoComplPop
    update=yes
    accept_hostkey=yes
  sudo: no

- name: Install vim-fugitive
  git:
    repo=https://github.com/tpope/vim-fugitive.git
    dest=~/.vim/bundle/vim-fugitive
    update=yes
    accept_hostkey=yes
  sudo: no
